[package]
name = "feudle_smart_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.3.1"
solana-program = "1.18.3"


[lib]
name = "feudle_smart_contract"
crate-type = ["cdylib", "lib"]
